### ISSUE TITLE
using q after man groff exits with status 127

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/man-dbport#11]
RC=(0) [SYSA] bash-5.2$ man groff
ҋx▒2(▒E0▒X8▒W▒▒7h▒▒D▒▒0▒▒1▒▒6▒,@▒#ҨX▒Ѱ▒טҡ ▒▒▒ۈ▒Ө▒ՠ▒ ҇▒▒^ қ▒җ▒▒▒: command exited with status 127:
 iconv -c -f UTF-8 -t ISO-8859-1//TRANSLIT | sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' |
 LESS=-ix8RmPm Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%..
 (press h for help or q to quit)$PM Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%..
 (press h for help or q to quit)$ MAN_PN=groff(1) less

**Comment by MikeFultonDev** [comment]
I also got an error - not really better - just different:
```
FULTONM@ZOSCAN2B bash ~/zopen/dev >man groff
CEE3204S The system detected a protection exception (System Completion Code=0C4).
         From compile unit zopen-ci1:./error.c at entry point error at statement 318 at compile unit offset +000000002697A1B2 at entry offset +00000000000000E2 at address 000000002697A1B2.
SIGSEGV
```

Looking at the traceback:
```
    6     __fprintf_a +00000A20              CELQLIB                                             HLE77C0  Exception
    7     error       +000000E2  318         man                  error.c                                 Call
    8     format_display
                      +00000886  170         man                  man.c                                   Call
    9     display     +00000EE8  2487        man                  man.c                                   Call
    10    display_filesystem
                      +000001AE  3242        man                  man.c                                   Call
    11    display_pages
                      +00000230  3636        man                  man.c                                   Call
    12    man         +000002AE  4001        man                  man.c                                   Call
    13    main        +00000BC6  4020        man                  man.c                                   Call
```

this is likely because it was trying to print out an error. That particular issue is open in: #5

**Comment by MikeFultonDev** [comment]
This doesn't happen for other 'man' requests, e.g. man man
I now get a 'better' error message.
I think it's because groff has the sequence:

```
\[oq]\-\[cq]
```

which renders as <B4> because it is being converted to ASCII (instead of UTF-8).

**Comment by MikeFultonDev** [comment]
I was able to validate that the basic piping seems ok:
```
#!/bin/sh

export LESS="-ix8RmPm Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)\$PM Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)\$"
export MAN_PN="groff(1)"
iconv -c -f UTF-8 -t ISO-8859-1//TRANSLIT <groff.man  | sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | less
```

but the 'input' of groff.man is not right - I have to flesh that out.

**Comment by MikeFultonDev** [comment]
When I set my terminal to western ASCII instead of utf-8, i don't seem to get that <B4> anymore. 
![image](https://user-images.githubusercontent.com/61100689/228932972-3dd3053e-1310-4ef6-92f0-c331e627b168.png)

**Comment by MikeFultonDev** [comment]
Expanding the script:
```
#!/bin/sh
export PATH=$HOME/zopen/prod/man-db-2.10.2/libexec/man-db:$PATH

zsoelim <groff.man | manconv -f UTF-8:ISO-8859-1 -t UTF-8//IGNORE | preconv -e UTF-8 | tbl | nroff -mandoc -rLL=203n -rLT=203n -Tutf8 >groff.massage

export LESS="-ix8RmPm Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)\$PM Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)\$"
export MAN_PN="groff(1)"
iconv -c -f UTF-8 -t ISO-8859-1//TRANSLIT <groff.massage  | sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | less
```

I get the warning:
```
troff: /home/fultonm/zopen/prod/groff/share/groff/1.22.4/tmac/an-old.tmac:696: warning: can't find macro file 'man.local'
```

**Comment by MikeFultonDev** [comment]
I also see I get the `<B4>` now...

**Comment by MikeFultonDev** [comment]
I confirmed that the warning is also printed out if I run 'man man' (e.g. I change the script as follows):
```
#!/bin/sh
input="$HOME/zopen/prod/groff-1.22.4/share/man/man1/groff.1"
input="$HOME/zopen/prod/man-db-2.10.2/share/man/man1/man.1"
export PATH=$HOME/zopen/prod/man-db-2.10.2/libexec/man-db:$PATH

zsoelim <${input} | manconv -f UTF-8:ISO-8859-1 -t UTF-8//IGNORE | preconv -e UTF-8 | tbl | nroff -mandoc -rLL=203n -rLT=203n -Tutf8 >groff.massage

export LESS="-ix8RmPm Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)\$PM Manual page groff(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)\$"
export MAN_PN="groff(1)"
iconv -c -f UTF-8 -t ISO-8859-1//TRANSLIT <groff.massage  | sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | less
```

So the warning isn't the problem.

**Comment by MikeFultonDev** [comment]
doing a binary divide of the input file, it appears that 
```
system within the free software collection
.UR http://\:www.gnu.org
GNU
.UE .
```

introduces the failure of '127' and that it is iconv that is failing (it says 256 but this is presumably 'massaged' from checking errno.

**Comment by MikeFultonDev** [comment]
groff docs https://www.man7.org/linux/man-pages/man7/groff_man.7.html states:
```
/usr/local/share/groff/1.23.0/tmac/an-ext.tmac
              Definitions of macros described above as extensions
              (.SY/.YS, .TQ, .EX/.EE, .UR/.UE, .MT/.ME, and .MR) are
              contained in this file;
```

**Comment by MikeFultonDev** [comment]
On z/OS, the .UR / .UE renders as:
![image](https://user-images.githubusercontent.com/61100689/228975689-cf56a32e-a2c8-4af2-a8ec-3dbfad6cca47.png)


On the Mac (where I don't get an error), the .UR / .UE renders as:
![image](https://user-images.githubusercontent.com/61100689/228975817-94520dc5-ed9c-4800-819b-9fa497d5c02a.png)

(the mac has the `<` and `>` around the URL)

**Comment by MikeFultonDev** [comment]
Looking at the intermediate UTF-8 file, the text does not render properly on z/OS but does render properly on my Mac:

GNU ⟨http://www.gnu.org⟩.

The angled brackets are UTF-8 angled brackets. 

```
cat /tmp/4025.txt | iconv -f UTF-8 -t ISO-8859-1//TRANSLIT >/tmp/out

iconv: (stdin):20:54: cannot convert
```

I get this same failure on my Mac:

```
cat 4025.txt | iconv -f UTF-8 -t ISO-8859-1//TRANSLIT >4025.ascii

iconv: (stdin):20:54: cannot convert
```

which either indicates the groff man page is in error, there is a bug in man-db, or the Mac 'built in' iconv for man is different than the one I am using on z/OS.

**Comment by MikeFultonDev** [comment]
The 2 UTF-8 code points are:
```
 E2 9F A8 ⟨
 E2 9F A9 ⟩
```

**Comment by MikeFultonDev** [comment]
looks like they should be valid:
https://www.compart.com/en/unicode/U+27E8 and https://www.compart.com/en/unicode/U+27E9

**Comment by gngrossi** [comment]
bash-5.2$ man grep
man: command exited with status 127: iconv -c -f UTF-8 -t ISO-8859-1//TRANSLIT | sed -e '/^[[:space:]]*$/{ N; /^[[:space:]]*\n[[:space:]]*$/D; }' | LESS=-ix8RmPm Manual page grep(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$PM Manual page grep(1) ?ltline %lt?L/%L.:byte %bB?s/%s..?e (END):?pB %pB\%.. (press h for help or q to quit)$ MAN_PN=grep(1) less

**Comment by MikeFultonDev** [comment]
thanks. i hadn't seen this. perhaps it is another issue similar to angled brackets. will investigate.

**Comment by MikeFultonDev** [comment]
@gngrossi I was able to reproduce this with the libiconv in 'prod' but it works when I build my own libiconv from the dev line, so I will leave this open until and figure out why libiconv wasn't built in jenkins.

**Comment by gngrossi** [comment]
Looks good...clean exit after q

RC=(0) [SYSA] bash-5.2$ man groff
RC=(0) [SYSA] bash-5.2$ man grep
RC=(0) [SYSA] bash-5.2$
