### ISSUE TITLE
man-db .env is not pulling in libiconv

### ISSUE THREAD

**Issue by MikeFultonDev** [ZOSOpenTools/man-dbport#18]
Even though we specify:
```
export ZOPEN_RUNTIME_DEPS="groff libiconv less ncurses"
```

the generated .env is not pulling in the program `iconv` (which is part of libiconv) and is required.
Not sure if the runtime env var spec is wrong or if the `zopen build` code has a problem. 

I see .runtimedeps in the generated install but I don't see any reference to it in the .env

**Comment by IgorTodorovskiIBM** [comment]
I'm unable to reproduce it:
* Did a `zopen install man-db`
* cd to ` ~/zopen/prod/man-db`
* Started a clean environment
```
[ITODORO@ZOSCAN2B ~/zopen/prod/man-db]$ /bin/env -i /bin/sh
$ export  _BPXK_AUTOCVT=ON
$ env
_BPXK_AUTOCVT=ON
_CEE_RUNOPTS=AL(ON) ABT(ABEND) POS(ON) TER(DUMP,CESE   ,96) FILET(AUTOCVT,AUTOTAG)
_=/bin/env
$ . ./.env
$ type iconv
iconv is /home/itodoro/zopen-data/prod/libiconv-1.17/bin/iconv
```

**Comment by IgorTodorovskiIBM** [comment]
`.depsenv` has this:
```
if [ -f "../libiconv/.env" ]; then
  if [[ $(type echo) == 'echo is a shell builtin' ]]; then
    pushd "../libiconv" >/dev/null
    . ./.env
    popd >/dev/null
  else
    cd "../libiconv" && . ./.env; cd - >/dev/null
  fi
fi
```

**Comment by MikeFultonDev** [comment]
when i do:
```
zopen install man-db
```
and then do:
`cd $HOME/zopen/prod/man`
I don't see a `.depsenv` file
and when I run `. ./.env` and then do:
`type -a iconv`
I still get `/bin/iconv`
