### ISSUE TITLE
tried man man .

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/man-dbport#20]
Got this 

![image](https://user-images.githubusercontent.com/42328411/236037742-62ffd858-1d42-4e1d-8883-69c6531b0602.png)

**Comment by MikeFultonDev** [comment]
please try again - i think this should work now although i haven't tried via omvs

**Comment by MikeFultonDev** [comment]
after working with @lbdyck i believe this is now ok - the key is to know that mandb must be run to create an index.
@lbdyck re-open if still not working from your perspective.
