### ISSUE TITLE
man -k . fails

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/man-dbport#21]
This works with the provided man but not with this one:

![image](https://user-images.githubusercontent.com/42328411/236038772-0d4fe15c-4cce-42b0-bfc3-9e653b577736.png)

**Comment by MikeFultonDev** [comment]
thanks @lbdyck . The reason I hadn't seen this is that it 'works' if you build it yourself but of course, that shouldn't be required. I'll figure out where the hardcoded path is coming from.

**Comment by MikeFultonDev** [comment]
I see that the Makefile.am has:
```
AM_CPPFLAGS = \
  -I$(top_srcdir)/include \
  -I$(top_builddir)/gl/lib \
  -I$(top_srcdir)/gl/lib \
  -I$(top_srcdir)/lib \
  -I$(top_srcdir)/libdb \
  -DCONFIG_FILE=\"$(config_file)\" \
  -DAPROPOS=\"$(bindir)/$(TRANS_APROPOS)\" \
  -DAPROPOS_NAME=\"$(TRANS_APROPOS)\" \
  -DMAN=\"$(bindir)/$(TRANS_MAN)\" \
  -DMANCONV=\"$(pkglibexecdir)/$(TRANS_MANCONV)\" \
  -DMANDB=\"$(bindir)/$(TRANS_MANDB)\" \
  -DWHATIS=\"$(bindir)/$(TRANS_WHATIS)\" \
  -DZSOELIM=\"$(pkglibexecdir)/$(TRANS_ZSOELIM)\"
```
These are all going to be issues, but `  -DAPROPOS=\"$(bindir)/$(TRANS_APROPOS)\" ` is what is causing the problem (I expect) here. I'll try just changing that to `-DAPROPOS=\"$(TRANS_APROPOPOS)\"` and see if that works ok

**Comment by MikeFultonDev** [comment]
This does indeed solve the problem but I am now getting 2 testcase failures instead of 1 so am investigating

**Comment by MikeFultonDev** [comment]
should be working now. Please get the latest man-db - you can use zopen-setup if you want to pull in all the stuff you need into 'boot' or alternately just refresh man-db and the dynamic tools it needs

**Comment by MikeFultonDev** [comment]
Hm. Can you screen shot your output? Are you running under bash or sh ? If bash which bash?

**Comment by MikeFultonDev** [comment]
after discussion with @lbdyck i believe this is now fixed. @lbdyck re-open if not
