### ISSUE TITLE
missing man page ????

### ISSUE THREAD

**Issue by lbdyck** [ZOSOpenTools/man-dbport#27]
attempting a `man sleep`

![image](https://github.com/ZOSOpenTools/man-dbport/assets/42328411/2da47e7c-b58a-4c21-a756-183bf89bc6fa)

**Comment by MikeFultonDev** [comment]
@lbdyck can you retry with latest man? I get:

man sleep
![image](https://github.com/ZOSOpenTools/man-dbport/assets/61100689/2aa2c89d-44ee-40b6-881d-4953dd507942)
