### ISSUE TITLE
whatis

### ISSUE THREAD

**Issue by gngrossi** [ZOSOpenTools/man-dbport#29]
Not sure what to expect...
thanks

# output from a Linux on Z RHEL 7.x server
$ whatis ls
ls (1p)              - list directory contents
ls (1)               - list directory contents

# output from an x86 RHEL 8.x server
$ whatis ls
ls: nothing appropriate.

--

RC=(0) [SYSA] bash-5.2$ which whatis
/hewitt/zopentools/guild/man-db-2.10.2/bin/whatis

RC=(0) [SYSA] bash-5.2$ whatis ls
ls: nothing appropriate.

RC=(16) [SYSA] bash-5.2$ whatis --version
whatis 2.10.2

RC=(0) [SYSA] bash-5.2$ whatis --help
Usage: whatis [OPTION...] KEYWORD...

  -d, --debug                emit debugging messages
  -v, --verbose              print verbose warning messages
  -r, --regex                interpret each keyword as a regex
  -w, --wildcard             the keyword(s) contain wildcards
  -l, --long                 do not trim output to terminal width
  -C, --config-file=FILE     use this user configuration file
  -L, --locale=LOCALE        define the locale for this search
  -m, --systems=SYSTEM       use manual pages from other systems
  -M, --manpath=PATH         set search path for manual pages to PATH
  -s, --sections=LIST, --section=LIST
                             search only these sections (colon-separated)
  -?, --help                 give this help list
      --usage                give a short usage message
  -V, --version              print program version

Mandatory or optional arguments to long options are also mandatory or optional
for any corresponding short options.
Report bugs to cjwatson@debian.org.

**Comment by MikeFultonDev** [comment]
@gngrossi Both `whatis` and` apropos` require that you run `mandb` on the GNU man pages to generate an index.
After you've done this, you can see one-liners for matching man pages for whatis. For example: `whatis iconv` should print out:
![image](https://github.com/ZOSOpenTools/man-dbport/assets/61100689/28f49eab-6dd7-4498-a06c-f3fb83a68506)

You should see a raw text match of headers with apropos, e.g. `apropos iconv` should print out:
![image](https://github.com/ZOSOpenTools/man-dbport/assets/61100689/23c5da47-b9a4-4f49-bf9b-0766aee2bed0)

**Comment by MikeFultonDev** [comment]
Simplest way to get all the GNU man pages set up is:
```
cd ~/zopen/boot
mandb .
cd ~/zopen/prod
mandb .
```

This will setup indexes for your 'prod' and 'boot' tools

**Comment by gngrossi** [comment]
bash-5.2$ man --version
man 2.10.2

# after running mandb for the first time
[mandb_output.txt](https://github.com/ZOSOpenTools/man-dbport/files/11600436/mandb_output.txt)


bash-5.2$ whatis apropos
apropos (1)          - search the manual page names and descriptions

bash-5.2$ whatis iconv
iconv (1)            - character set conversion
iconv (3)            - perform character set conversion

bash-5.2$ whatis vim
vim (1)              - Vi IMproved, a programmer's text editor

**Comment by MikeFultonDev** [comment]
ok - what looks right to me. Any concerns or can we close?

**Comment by gngrossi** [comment]
Does this look OK for the mandb output?
thanks

mandb: warning: $MANPATH set, ignoring /u/jenkins/zopen/prod/man-db-2.10.2/etc/man_db.conf
mandb: warning: no MANDB_MAP directives in /u/jenkins/zopen/prod/man-db-2.10.2/etc/man_db.conf, using your manpath

EDC5129I No such file or directory.
mandb: warning:

Processing manual pages under /hewitt/coz/current/doc/man...
mandb: can't update index cache /hewitt/coz/current/doc/man/84546389: EDC5129I No such file or directory.
Updating index cache for path `/hewitt/coz/current/doc/man/man5'. Wait...done.
Checking for stray cats under /hewitt/coz/current/doc/man...
Processing manual pages under /hewitt/coz/current/doc/man/cat1...
mandb: can't update index cache /hewitt/coz/current/doc/man/cat1/84546389: EDC5129I No such file or directory.
Processing manual pages under /hewitt/coz/current/doc/man/cat5...
mandb: can't update index cache /hewitt/coz/current/doc/man/cat5/84546389: EDC5129I No such file or directory.

**Processing manual pages under /usr/lpp/ported/man/C...
mandb: warning: cannot create catdir /usr/lpp/ported/man/C/cat1**

Removing obsolete cat directory /hewitt/coz/current/doc/man/cat1/catsearch.1...

73 man subdirectories contained newer manual pages.
5746 manual pages were added.
0 stray cats were added.
0 old database entries were purged.

**Comment by gngrossi** [comment]
I ran:
bash-5.2$ pwd
/hewitt/zopentools/guild

then mandb

**Should I run mandb . instead?**

**Also, the update below, was that OK?**

Processing manual pages under /hewitt/coz/current/doc/man...
mandb: can't update index cache /hewitt/coz/current/doc/man/84546389: EDC5129I No such file or directory.
Updating index cache for path `/hewitt/coz/current/doc/man/man5'. Wait...done.
Checking for stray cats under /hewitt/coz/current/doc/man...
Processing manual pages under /hewitt/coz/current/doc/man/cat1...
mandb: can't update index cache /hewitt/coz/current/doc/man/cat1/84546389: EDC5129I No such file or directory.
Processing manual pages under /hewitt/coz/current/doc/man/cat5...
mandb: can't update index cache /hewitt/coz/current/doc/man/cat5/84546389: EDC5129I No such file or directory.

**Removing obsolete cat directory /hewitt/coz/current/doc/man/cat1/catsearch.1...**

**Comment by gngrossi** [comment]
bash-5.2$ pwd
/hewitt/zopentools/guild

bash-5.2$ mandb .
[mandb_output2.txt](https://github.com/ZOSOpenTools/man-dbport/files/11601454/mandb_output2.txt)

**Comment by gngrossi** [comment]
Closing issue and opening a new issue "Validate messages from mandb".
