### ISSUE TITLE
Tarball build of man-db fails because /usr/include/le/ndbm.h is outdated and dptr is void* rather than char*

### ISSUE THREAD

**Issue by IgorTodorovskiIBM** [ZOSOpenTools/man-dbport#4]
We probably need to port https://github.com/LuaDist/libgdbm to progress forward.  The current issue is:

```
./db_lookup.c:303:30: error: invalid operands to binary expression ('void' and 'int')
        else if (*MYDBM_DPTR (cont) != '\t') {  /* Just one entry */
```
This is because dptr is void* rather than char*.

**Comment by MikeFultonDev** [comment]
issue opened: https://github.com/ZOSOpenTools/gdbmport/issues/1 (looks like gdbm isn't building correctly)

**Comment by MikeFultonDev** [comment]
fixed
